#!/usr/bin/env node
// Produces local raster frames from original SVG graphics. No imagery, logos,
// or text is generated by a model; every text string below is locked script
// copy or verified end-card copy.

import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const output = process.argv[2];
if (!output) {
  throw new Error('Usage: render_review_graphics.mjs <output-directory>');
}

await mkdir(output, { recursive: true });

const palette = {
  cream: '#F7F2E8',
  gold: '#F3D36A',
  green: '#80C6A1',
  navy: '#071B2E',
  navySoft: '#102B45',
};

const esc = (value) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');

function text(textValue, x, y, size, color = palette.cream, weight = 700, anchor = 'middle') {
  return `<text x="${x}" y="${y}" fill="${color}" font-family="Arial, Helvetica, sans-serif" font-size="${size}" font-weight="${weight}" text-anchor="${anchor}" letter-spacing="1">${esc(textValue)}</text>`;
}

function marker(x, y, color = palette.green, radius = 16) {
  return `<circle cx="${x}" cy="${y}" r="${radius}" fill="${color}" stroke="${palette.cream}" stroke-opacity=".45" stroke-width="2"/>`;
}

function pitch(content) {
  return `
    <svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720">
      <defs>
        <pattern id="grid" width="80" height="80" patternUnits="userSpaceOnUse"><path d="M 80 0 L 0 0 0 80" fill="none" stroke="${palette.cream}" stroke-opacity=".10" stroke-width="1"/></pattern>
        <linearGradient id="field" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${palette.navySoft}"/><stop offset="1" stop-color="${palette.navy}"/></linearGradient>
      </defs>
      <rect width="1280" height="720" fill="url(#field)"/>
      <rect width="1280" height="720" fill="url(#grid)"/>
      <rect x="100" y="96" width="1080" height="528" rx="8" fill="none" stroke="${palette.cream}" stroke-opacity=".30" stroke-width="3"/>
      <path d="M640 96V624M100 360H1180M148 220H228V500H148M1052 220H1132V500H1052" fill="none" stroke="${palette.cream}" stroke-opacity=".22" stroke-width="3"/>
      <circle cx="640" cy="360" r="66" fill="none" stroke="${palette.cream}" stroke-opacity=".18" stroke-width="3"/>
      ${content}
    </svg>`;
}

const scenes = [
  pitch(`
    <path d="M190 496 C350 420, 488 470, 624 344 S870 226, 1040 258" fill="none" stroke="${palette.gold}" stroke-width="8" stroke-linecap="round" stroke-dasharray="16 18"/>
    ${marker(210, 480)}${marker(438, 408)}${marker(720, 300)}${marker(1000, 242)}
    ${marker(164, 492, palette.gold, 19)}
    ${text('Every kingdom starts with one decision:', 640, 82, 42)}
    ${text('show up.', 640, 144, 66, palette.gold)}
  `),
  pitch(`
    <path d="M320 506 C420 460, 500 398, 584 338" fill="none" stroke="${palette.gold}" stroke-width="8" stroke-linecap="round"/>
    <path d="M555 320 l44 18 -24 40" fill="none" stroke="${palette.gold}" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
    ${marker(360, 480, palette.gold, 21)}${marker(505, 394)}${marker(660, 318)}${marker(820, 258)}
    ${text('Train the skill.', 640, 86, 60)}
    ${text('Build the discipline.', 640, 152, 60, palette.gold)}
  `),
  pitch(`
    <rect x="164" y="152" width="310" height="194" rx="12" fill="${palette.cream}" fill-opacity=".12" stroke="${palette.cream}" stroke-opacity=".32" stroke-width="3"/>
    <path d="M204 196H430M204 230H390M204 264H418" stroke="${palette.cream}" stroke-opacity=".36" stroke-width="9" stroke-linecap="round"/>
    ${marker(760, 222)}${marker(842, 276)}${marker(800, 372)}${marker(694, 334)}${marker(776, 300, palette.gold, 21)}
    ${text('Because the game can open doors', 640, 514, 46)}
    ${text('— but character is what carries you through them.', 640, 574, 36, palette.gold)}
  `),
  pitch(`
    <path d="M230 278 L370 358 L510 438 L650 358 L790 278" fill="none" stroke="${palette.gold}" stroke-width="8" stroke-linecap="round" stroke-dasharray="12 16"/>
    <path d="M280 506 C430 430, 565 440, 720 334" fill="none" stroke="${palette.green}" stroke-width="7" stroke-linecap="round"/>
    ${marker(232, 276, palette.gold, 17)}${marker(372, 356, palette.gold, 17)}${marker(512, 436, palette.gold, 17)}${marker(652, 356, palette.gold, 17)}${marker(792, 276, palette.gold, 17)}
    ${marker(294, 494, palette.gold, 22)}${marker(550, 420)}${marker(750, 316)}
    ${text('We develop leaders ready for', 640, 82, 52)}
    ${text('the next play and the next chapter.', 640, 142, 46, palette.gold)}
  `),
  pitch(`
    <rect x="578" y="292" width="124" height="124" rx="62" fill="${palette.gold}" fill-opacity=".18" stroke="${palette.gold}" stroke-width="4"/>
    ${marker(640, 354, palette.gold, 20)}${marker(480, 354)}${marker(800, 354)}${marker(640, 514)}${marker(640, 194)}
    ${text('THE BALLERS KINGDOM', 640, 86, 62)}
    ${text('BUILD YOUR KINGDOM', 640, 148, 42, palette.gold)}
    ${text('ballkingdom.com', 640, 612, 36)}
  `),
];

await Promise.all(scenes.map((scene, index) => sharp(Buffer.from(scene)).png().toFile(path.join(output, `scene-${index + 1}.png`))));
